run:
  timeout: 5m

linters-settings:
  gocritic:
    enabled-tags:
    - performance
  gosec:
    excludes:
    - G108
  lll:
    line-length: 200

  misspell:
    locale: US

  revive:
    enable-all-rules: true
    rules:
      - name: dot-imports
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: add-constant
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: import-alias-naming
        disabled: true
      - name: early-return
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: deep-exit
        disabled: true
      - name: unhandled-error
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: function-length
        disabled: true
      - name: comment-spacings
        disabled: true
      - name: struct-tag
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - forcetypeassert
    - gocritic
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - revive # replacement for golint
    - staticcheck
    - typecheck
    - unused
    - whitespace
